### ISSUE TITLE
Bug: JSONDecodeError()

### ISSUE THREAD

**Issue by variableVG** [FreshJonas/NLP-on-Movie-Plots#1]
![image](https://user-images.githubusercontent.com/58001220/199262794-2db0093f-9174-431c-88ee-fa5d829fad7b.png)

**Comment by variableVG** [comment]
Also, what is level=0 and max_level=1?

**Comment by variableVG** [comment]
Also, what is max_level in get_pagesInCategory? Because then in the function get_pagesInCategory, when the recursion call is made, the value is not changed. So ... in principle, why do we need this parameter? 

![image](https://user-images.githubusercontent.com/58001220/199264237-b3287452-919b-456e-9b77-2ad9fb31de98.png)

**Comment by FreshJonas** [comment]
Hmm thats weird. I just tried it again and I dont get the JSON Decode Error.

**Comment by FreshJonas** [comment]
The max_level parameter determines how many levels "deep" the recursion should occur. For example max_level = 0 would lead to a result in which only pages that are directly listed under the given categorymembers are shown. When max_level = 1 it also look at the pages that are listed under one of these pages and so on. This way we can modify how many datapoints are getting aquired.

**Comment by variableVG** [comment]
> Hmm thats weird. I just tried it again and I dont get the JSON Decode Error.

It does not happen always. I think it might be that some page is not found for some reason (maybe the internet has some problem). If that happens, then the loop does not continue and the thing crashes. Maybe at some point, it could be good to put that in a try/except.
