### ISSUE TITLE
04_02 PreProcessed Version does not work for validating Model with Testing Data

### ISSUE THREAD

**Issue by variableVG** [FreshJonas/NLP-on-Movie-Plots#4]
(Jonas)
I am currently trying to implement a custom pre processing to the PyTorch Classifcation seen in 04_01. The current version in 04_02 works partly. I am able to use the model (takes 10 times longer as in 04_01) but I am not able to verify the model by using the testing data.

So there are two issues.

    PreProcessing being extremely slow in comparison to 04_01
    PreProcessed Version does not work for validating Model with Testing Data

**Comment by variableVG** [comment]
I do not know what you mean in this issue. I was able to run the code without any complaints of that type. Do you mean this last part? 

![image](https://user-images.githubusercontent.com/58001220/200576724-20967614-ab54-495e-9753-4fd31f6efe73.png)

It did work for me. I upload that in my branch, in case you need to look at it.

**Comment by FreshJonas** [comment]
Fixed:

**Comment by FreshJonas** [comment]
Issue was due to an off by one error.
Since the vocab can also include the value 0 for words that are not parts of the vocabulary but are not removed in the cleaning.
This is why the vocabulary_size has to be enlarged by one
